# Generated by Django 5.0.7 on 2026-06-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='was_overdue',
            field=models.BooleanField(default=False, verbose_name='是否曾经逾期'),
        ),
    ]
